## YAML Template.
---
mysql: 
    container_name: mysql_container
    restart: always
    image: mysql/mysql-server:5.7
    environment:
        MYSQL_ROOT_PASSWORD: 'sql_password'
    volumes:
        - ./bindpoints/mysqldatabase:/var/lib/mysql
    ports:
        - 3306:3306